version: '3.8'

services:
  server:
    build:
      dockerfile: Dockerfile
      context: "./nodejs-server"
    ports:
      - 5001:5001
    networks:
      - computer-science-project

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:3000
    networks:
      - computer-science-project

networks:
  computer-science-project:
    driver: bridge