version: '3.8'

services:
  server:
    build:
      dockerfile: Dockerfile
      context: "./nodejs-server"
    ports:
      - 5001:5001

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:3000
    environment:
      - REACT_APP_HOSTNAME=http://13.236.73.101:5001
