version: '3.8'

services:
  csp-server:
    build:
      dockerfile: Dockerfile
      context: "./nodejs-server"
    ports:
      - 5001:5001
    networks:
      - csp

  csp-client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:3000
    environment:
      - REACT_APP_NODE_IP=host.docker.internal
    networks:
      - csp
  
networks:
  csp:
    driver: bridge