version: '3.8'

services:
  server:
    build:
      dockerfile: Dockerfile
      context: "./nodejs-server"
    container_name: nodeserver
    ports:
      - 5001:5001
    networks:
      - computer-science-project

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    container_name: reactclient
    ports:
      - 3000:3000
    environment:
      - REACT_APP_NODE_IP=nodeserver
    networks:
      - computer-science-project

networks:
  computer-science-project:
    driver: bridge